const data = {
    products: [
        {
            name: "Free Shirt",
            slug: "free-shirt",
            category: "Shirts",
            image: "/images/shirt1.jpg",
            price: 70,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: "A popular shirt",
        },
        {
            name: "Fit Shirt",
            slug: "fit-shirt",
            category: "Shirts",
            image: "/images/shirt2.jpg",
            price: 40,
            brand: "Adidas",
            rating: 4,
            numReviews: 10,
            countInStock: 20,
            description: "A fit shirt",
        },
        {
            name: "Polo",
            slug: "polo",
            category: "Ralph Lauren",
            image: "/images/shirt3.jpg",
            price: 90,
            brand: "Nike",
            rating: 4.8,
            numReviews: 10,
            countInStock: 20,
            description: "A polo",
        },
        {
            name: "Casual Shirt",
            slug: "casual-shirt",
            category: "Shirts",
            image: "/images/shirt4.jpg",
            price: 60,
            brand: "Adidas",
            rating: 4.5,
            numReviews: 10,
            countInStock: 20,
            description: "A popular shirt",
        },
        {
            name: "Sport Shirt",
            slug: "sport-shirt",
            category: "Shirts",
            image: "/images/shirt5.jpeg",
            price: 30,
            brand: "Nike",
            rating: 5,
            numReviews: 10,
            countInStock: 20,
            description: "A sportive shirt",
        },
        {
            name: "Basketball Shorts Adidas",
            slug: "basketball-shorts",
            category: "Pants",
            image: "/images/pants1.jpg",
            price: 45,
            brand: "Adidas",
            rating: 3.9,
            numReviews: 10,
            countInStock: 20,
            description: "Some Basketball shorts",
        },
        {
            name: "Casual Shoes",
            slug: "casual-shoes",
            category: "Shoes",
            image: "/images/shoes1.jpg",
            price: 130,
            brand: "Nike",
            rating: 4.1,
            numReviews: 10,
            countInStock: 20,
            description: "Some casual shoes",
        },
    ],
};

export default data;
